### ISSUE TITLE
asciidoctorj-pdf does not render images with special chars in title

### ISSUE THREAD

**Issue by matthiasbalke** [asciidoctor/asciidoctorj-pdf#12]
When using brackets within the title of an image, the image is not getting rendered with asciidocj-pdf.

```adoc
[[img.some-reference]]
image::images/image.png[title="Schaltfläche [Filter]"]
```
As soon as I remove the brackets it's rendering the image just fine. Also I can escape the last bracket, which also renders fine.
```adoc
[[img.some-reference]]
image::images/image.png[title="Schaltfläche [Filter\]"]
```

The image is also displayed fine without escaping when using the IntelliJ preview. 

**versions**
asciidoctor-gradle-plugin=1.5.3
asciidoctorj=1.6.0-alpha.4
asciidoctorj_pdf=1.5.0-alpha.15
AsciiDoc (IntelliJ plugin)=0.19.1

**Comment by robertpanzer** [comment]
I think this issue better belongs to https://github.com/asciidoctor/asciidoctor-pdf
asciidoctorj-pdf really just is a repackaging of the Ruby Gems into a Jar so that they are consumable by asciidoctorj.

**Comment by matthiasbalke** [comment]
@robertpanzer I wasn't sure about where to file the issue. I will move it. Thanks for letting me know.
