### ISSUE TITLE
Footnote doesn't render under paragraph

### ISSUE THREAD

**Issue by Solido** [asciidoctor/asciidoctorj-pdf#18]
Screenshot from IntelliJ plugin preview
<img width="543" alt="screenshot 2018-10-28 at 12 06 51" src="https://user-images.githubusercontent.com/1295961/47615061-3f886900-daaa-11e8-9268-63e7293a72a9.png">

Screenshot from the rendered Pdf.
<img width="525" alt="screenshot 2018-10-28 at 12 07 12" src="https://user-images.githubusercontent.com/1295961/47615062-4020ff80-daaa-11e8-8188-7190f2d450f9.png">

Thank you.

**Comment by robertpanzer** [comment]
Hi Robert,

this issue would better fit into the repo https://github.com/asciidoctor/asciidoctor-pdf.
Asciidoctorj-pdf is just a small Java wrapper around asciidoctor-pdf, and this seems to be related to the core rendering logic of asciidoctor-pdf.

**Comment by Solido** [comment]
Thanks !
