### ISSUE TITLE
Release version 1.5.0?

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctorj-pdf#20]
The latest version in Maven Central is still 1.5.0-alpha.16. Is there going to be an official 1.5.0 ? Also are there versions planned that will be aligned with asciidoctorj 1.6.x and 2.x.x ?

**Comment by robertpanzer** [comment]
Asciidoctorj-pdf is basically just a repackaging of asciidoctor/asciidoctor-pdf without any additions.
As such it is aligned to the same versioning.
Asciidoctor-pdf is also at 1.5.0-alpha.16, therefore Asciidoctorj-pdf has the same version.

**Comment by mojavelinux** [comment]
As @robertpanzer, asciidoctor-pdf is still marching towards 1.5.0 and 2.0.0. As soon as that happens, it will happen here.

> Also are there versions planned that will be aligned with asciidoctorj 1.6.x and 2.x.x ?

The version of AsciidoctorJ PDF is independent of the version of AsciidoctorJ. I've worked hard to maintain compatibility with both version lines of Asciidoctor / AsciidoctorJ (1.5.8 and 2.0.x). If something doesn't work, just let us know and we'll address it.

FYI, the hold up on releasing Asciidoctor PDF 1.5.0 was the fact that it didn't have any tests. Now it has > 200. There are just a few remaining items to address, then we'll proceed with the 1.5.0 release, then likely do a 2.0.0 shortly thereafter.

**Comment by mojavelinux** [comment]
To keep you updated, 1.5.0-beta.2 is now available. We're getting closer to 1.5.0 and 2.0.0, but not there just yet.

**Comment by Bl4d3s** [comment]
Now 1.5.0-beta3 is available, but here the latest release is 1.5.0-alpha18. Can this be updated?

**Comment by robertpanzer** [comment]
I forgot to push the tags, but beta.2 is available: https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-pdf/1.5.0-beta.2/jar
I’ll make a release of beta.3 ASAP.

**Comment by mojavelinux** [comment]
And just to keep you updated, we're still on the march to 1.5.0. There are few more important change I need to make to the internals, in addition to any bugs that come up. Once that's done, I'll plow the open issues away and make the 1.5.0 release. We're getting very close.

**Comment by robertpanzer** [comment]
@Bl4d3s asciidoctorj-pdf 1.5.0-beta.4 is available now.

**Comment by thekalinga** [comment]
Is this release `1.5.0-beta.4` compatible with for `asciidoctor-gradle-plugin` `2.0.0`+?

**Comment by mojavelinux** [comment]
It should be, yes.

**Comment by pvorb** [comment]
I suppose this issue can be closed now that 1.5.0 has been released.

**Comment by mojavelinux** [comment]
Oh yes! Thanks for catching it!
