### ISSUE TITLE
Update to Asciidoctor-pdf 1.15.0.alpha.17

### ISSUE THREAD

**Issue by programming-wolf** [asciidoctor/asciidoctorj-pdf#21]
Hi there.
First off, thank you for your work with this wrapper for asciidoctor-pdf. 
There was a new release of asciidoctor-pdf a few weeks ago to version 1.15.0.alpha.17. Will you create a new release for this and push it to maven central etc.?

Thanks!

**Comment by robertpanzer** [comment]
Hi Ben,

thank you! :)

I guess it should be already here: https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.17/jar
Do you get errors when you try to load it?

**Comment by programming-wolf** [comment]
Hi Robert. I am so sorry. I didn't see a release on this repository, and I also misspelled the file name, I used `.` instead of `-`. 🤦‍♂  I got an error message and thought that there is no release. 
Apologies. It works as expected.
