### ISSUE TITLE
Update to asciidoctor-pdf 1.5.0 beta

### ISSUE THREAD

**Issue by programming-wolf** [asciidoctor/asciidoctorj-pdf#23]
Hi, when will asciidoctorj-pdf be updated to use asciidoctor-pdf 1.5.0-beta.1? This time, I am pretty confident that I did not misspell it and I also did not find it on maven.org . :-)

**Comment by robertpanzer** [comment]
You are right, I didn't make that release yet. ;)
As @mojavelinux pointed out on twitter that it has some problems and that a beta.2 is planned to be released soon I wanted to wait for this and skip beta.1.

**Comment by programming-wolf** [comment]
Fair enough, I didn’t see his tweet as I’m on holidays. 🙃 thanks for the quick reply!

**Comment by mojavelinux** [comment]
Yes, please wait for beta.2. It's almost ready.

>

**Comment by programming-wolf** [comment]
beta.2 is available. 🙂 Can I somehow help to create the release? Or is it just one configuration value anyway?

**Comment by robertpanzer** [comment]
Yes, I released it yesterday :+1: https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-pdf/1.5.0-beta.2/jar

**Comment by programming-wolf** [comment]
Thanks for that!

**Comment by mojavelinux** [comment]
Thanks @robertpanzer!
