### ISSUE TITLE
syntax error, unexpected kDO_BLOCK Float.prepend (Module.new do

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctorj-pdf#27]
Since 1.5.0-alpha.15 seems to have problems when I use AsciiDoc within tables, I just tried to use a newer version.
With all versions > 1.5.0-alpha.16 I get the following exception:

```
Caused by: org.jruby.exceptions.RaiseException: (SyntaxError) /home/rdmueller/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.17/89b2c69805e40ead99b580c38a292aebea19c849/
asciidoctorj-pdf-1.5.0-alpha.17.jar!/gems/asciidoctor-pdf-1.5.0.alpha.17/lib/asciidoctor-pdf/core_ext/numeric.rb:2: syntax error, unexpected kDO_BLOCK
Float.prepend (Module.new do
^
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
```

I know that this error is based at the asciidoctor-pdf (not the jruby wrapper) project, but I guess it could be related to the jRuby version used in the wrapper - that's why I report it here.
 
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor/pdf/ext/core/numeric.rb

used with 
```
     org.asciidoctor:asciidoctor-gradle-plugin:1.5.8
```

**Comment by robertpanzer** [comment]
Did you already try with the latest beta version?
If it’s not fixed there I  guess this issue better fits into asciidoctor/asciidoctor-pdf.

**Comment by rdmueller** [comment]
yep. tried with the latest beta.6
I now succeeded by upgrading the `asciidoctor-gradle-plugin` to V2.3.0
solved this issue for me - thanx!

**Comment by robertpanzer** [comment]
👍
