### ISSUE TITLE
asciidoctorj-pdf is not rendering Cylinder shape

### ISSUE THREAD

**Issue by myron-randall** [asciidoctor/asciidoctorj-pdf#34]
I am using the following versions in my pom using maven:
<asciidoctor.maven.plugin.version>2.0.0-RC.1</asciidoctor.maven.plugin.version>
<asciidoctorj.version>2.1.0</asciidoctorj.version>
<asciidoctorj.diagram.version>1.5.18</asciidoctorj.diagram.version>
<jruby.version>9.2.9.0</jruby.version>
<asciidoctorj.pdf.version>1.5.0-beta.7</asciidoctorj.pdf.version>

Here is a snipet of the code:
      subgraph cluster_storage_2 {
          label = "Persistent Storage";
          style=filled;
          fillcolor=dodgerblue2;
          disk3 [shape=cylinder, label="Disk 2", color=red, style=filled, fillcolor=pink]
          disk4 [shape=cylinder, label="Disk 1", color=blue, style=filled, fillcolor=lightblue]
      }

**Comment by robertpanzer** [comment]
Hi,

I cannot reproduce your description.
I created this document:
```adoc
= Test

Test

== Test

[graphviz,test,svg]
----
graph cluster_storage_2 {
label = "Persistent Storage";
style=filled;
fillcolor=dodgerblue2;
disk3 [shape=cylinder, label="Disk 2", color=red, style=filled, fillcolor=pink]
disk4 [shape=cylinder, label="Disk 1", color=blue, style=filled, fillcolor=lightblue]
}
----
```
and as a result I got this in my PDF:
<img width="219" alt="Screen Shot 2019-11-20 at 7 59 06 AM" src="https://user-images.githubusercontent.com/1163662/69254812-aa9c5600-0b6b-11ea-9c62-1cbe4634acc6.png">

Can you please provide an example that allows to reproduce your issue?
And also a description of what you see instead?

**Comment by myron-randall** [comment]
I am using Jenkins to run a maven build. My diagram is an external file that is pulled into the adoc. I am seeing boxes instead of cylinders.

**Comment by myron-randall** [comment]
Attached files:

![Capture](https://user-images.githubusercontent.com/32470861/69275742-d599a080-0b91-11ea-81a1-52a74cd8471e.PNG)

**Comment by robertpanzer** [comment]
Can you add which version of graphviz you have installed on that machine?
That should do the actual rendering.

**Comment by myron-randall** [comment]
Ouput from 
dot -v
dot - graphviz version 2.30.1 (20180420.1509)
libdir = "/usr/lib64/graphviz"
Activated plugin library: libgvplugin_pango.so.6
Using textlayout: textlayout:cairo
Activated plugin library: libgvplugin_dot_layout.so.6
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.so.6
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        /usr/lib64/graphviz/config6
                was successfully loaded.
    render      :  cairo dot fig map pic pov ps svg tk vml xdot
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  bmp canon cmap cmapx cmapx_np dot eps fig gtk gv ico imap imap_np ismap jpe jpeg jpg pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz x11 xdot xlib
    loadimage   :  (lib) eps gif jpe jpeg jpg png ps svg

**Comment by robertpanzer** [comment]
OK, it looks like your version of Graphviz is too old.
According to the changeling the cylinder shape was added in 2.40.0: https://gitlab.com/graphviz/graphviz/blob/master/ChangeLog#L41

**Comment by myron-randall** [comment]
ok, thank you! I'll see what I can do to get it updated to a newer version.
