### ISSUE TITLE
License issue from one dependency

### ISSUE THREAD

**Issue by mariuszpala** [asciidoctor/asciidoctorj-pdf#69]
Asciidoctorj-pdf library embeds ttfunk gem inside the jar/gems which is the only dependency on GPL license which makes the library impossible to be used in commercial projects. Can this gem be removed from the library?

![image](https://user-images.githubusercontent.com/12190923/153196806-ce94e53b-bdff-47a1-897e-3dc9e3b87ea4.png)

**Comment by mojavelinux** [comment]
It's not possible to remove ttfunk alone. The only solution to taking it out of the gem would be to use AsciidoctorJ and point to a gem installation that provides asciidoctor-pdf...essentially using it unbundled. AsciidoctorJ-PDF is merely a convenient distribution for users of AsciidoctorJ.

**Comment by mariuszpala** [comment]
Does it mean that the license for this library must be changed from Apache to GPL?

**Comment by mojavelinux** [comment]
No, it does not make sense. We will not be changing the license of this library. The gems are redistributed as part of the jar package, but the source code of those gems is not modified. This is permissible under "Matz's terms for Ruby", which is one of the libraries under which ttfunk is licensed. This is both stated in the README of that project and clarified the developer's themselves in the linked issue. To the best of my knowledge, we are in compliance with those terms.

**Comment by mariuszpala** [comment]
Everything is fine, it is clarified here: https://github.com/prawnpdf/ttfunk/issues/96
Thank you

**Comment by robertpanzer** [comment]
Thank you @mojavelinux !!!
I wouldn't have been able to answer this.
