### ISSUE TITLE
GitHub releases not in sync with maven central versions

### ISSUE THREAD

**Issue by de-jcup** [asciidoctor/asciidoctorj-pdf#71]
## Situation
I was a little bit curious if there is already a new version available at Github which is newer than the latest version on maven central:
https://mvnrepository.com/artifact/org.asciidoctor/asciidoctorj-pdf

On maven central I found: asciidoctorj pdf - version 1.6.2

But ... looking at https://github.com/asciidoctor/asciidoctorj-pdf/releases
the newest release is 1.6.0 ?!?

Looking at the tags, I found the 1.6.2 - so okay... - but at the first glance I was a little bit surprised

## Wanted
As GitHub is the source platform, all releases should be there as well.

## Proposal
I would suggest an automated release to maven  central via Github actions, which automatically creates corresponding GitHub releases and does tagging. I did this in one of my projects, see
https://github.com/de-jcup/eclipse-commons/blob/master/.github/workflows/release.yml
(but this one uses maven...)

For gradle there is also a description available:
- https://central.sonatype.org/publish/publish-gradle/
- I found also a good explanation here: https://github.com/jonashackt/github-actions-release-maven

**Comment by robertpanzer** [comment]
I had created a tag v1.6.2 and pushed it together with the release.
I have pushed the "Create Release" button now so that it also appears in the release list: https://github.com/asciidoctor/asciidoctorj-pdf/releases/tag/v1.6.2

**Comment by de-jcup** [comment]
@robertpanzer Shall I close my issue or do you think the automation would be still a good option?

**Comment by abelsromero** [comment]
You are right, we have been been messing the creation of GH releases but I see all of them in Maven repository  https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-pdf. The most recent is 2.0.8.

> In my opinion a robust and automatic release process that keeps everything in sync is fundamental. There seem to be some Github actions related to releases, but I haven't looked into them or what might be broken there as there are failing actions.

If you are familiar with it, it'd be great. I think we only need to create the release, event if it's empty.

**Comment by TheHaf** [comment]
Indeed they are present on the Maven repo, sorry, about creating more confusion.

Unfortunately I am not that familiar with Github actions, I only did a few Gitlab CI jobs in the past.

**Comment by robertpanzer** [comment]
I just created Github releases from the tags.
I still prefer to test the releases from the staging repository manually before publishing them to Maven central. Therefore I am currently hesitant about creating GH releases as part of the release pipeline.

**Comment by de-jcup** [comment]
@robertpanzer - Thank you :rocket:
