### ISSUE TITLE
Adopt asciidoctor-pdf 2.0.0

### ISSUE THREAD

**Issue by timtebeek** [asciidoctor/asciidoctorj-pdf#72]
https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v2.0.0

Not sure if there's any more work to do here in adoption past updating the version number. If not then perhaps something like Dependabot or Renovate could help surface new releases for adoption.

**Comment by robertpanzer** [comment]
I'll try to take care of this next weekend.

**Comment by robertpanzer** [comment]
Asciidoctorj-pdf 2.0.3 is already released and 2.0.4 should hit Maven central soon.
