### ISSUE TITLE
%breakable option on sections seems not to work as I expected it

### ISSUE THREAD

**Issue by TH-RBK** [asciidoctor/asciidoctorj-pdf#75]
Hi, 
one big problem in asciidoctor-pdf was that section titles may be separated from the first block of the section.

I thought, that a feature regarding this problem was implemented in 2.0.x, but I did not work as expected.

The [documentation](https://docs.asciidoctor.org/pdf-converter/latest/breakable-and-unbreakable/ ) tells me to put [%breakable] in the line before the title and I expected that the title **and** the following block got on the next page.

But as you see in the attached screenshot, the block is split over two pages.
![grafik](https://user-images.githubusercontent.com/3983994/174056915-dad33899-86fc-47d9-b83e-bfad52692002.png)

Here is the relevant code block.
```
Hier wird bis zur jeweiligen Maximalzahl aufgefüllt und bei Erreichen einer Maximalzahl wieder analog Schritt 6 die Suchmenge aufgeräumt.

[%breakable]
==== Schritt 11: XXXXXXX

Sollte XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 0 ist.

Auf XXXXXXX.
```

Am I doing something wrong or is this feature not implemented in asciidoctorj-pdf?

Thanks for your help!!!

**Comment by abelsromero** [comment]
This questions are better addressed at https://asciidoctor.zulipchat.com. Keep in mind `asciidoctorj-pdf` offers Java bindings for the asciidoctor-pdf Ruby gem.

**Comment by TH-RBK** [comment]
Thanks, for the information. I opened a thread on [zulip](https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/.25breakable.20option.20on.20sections.20seems.20not.20to.20work.20as.20I.20expect/near/286750660).
