### ISSUE TITLE
Version 2.3.4 missing in Maven repository

### ISSUE THREAD

**Issue by sopgreg** [asciidoctor/asciidoctorj-pdf#84]
See description, version 2.3.4 is currently missing im Maven repository:

https://mvnrepository.com/artifact/org.asciidoctor/asciidoctorj-pdf

**Comment by robertpanzer** [comment]
I just released and pushed a new version to Maven central.
It should appear at https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj-pdf/ in a few minutes.
