### ISSUE TITLE
Last releases not in Maven Central?

### ISSUE THREAD

**Issue by ilgrosso** [asciidoctor/asciidoctorj-pdf#95]
It seems that the last one available to Maven Central is 2.3.7: https://central.sonatype.com/artifact/org.asciidoctor/asciidoctorj-pdf/2.3.7/versions

**Comment by robertpanzer** [comment]
Thanks for reporting this.
I am pretty sure I pushed the release button.
The last release of asciidoctorj 2.5.10 itself, and previously 2.5.9 also did not make it there for some reason.
I created https://issues.sonatype.org/browse/MVNCENTRAL-8195 to follow up on this.

**Comment by robertpanzer** [comment]
The release is available now at https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj-pdf/2.3.9/
No idea if I missed pushing the release button or what happened, but it should be fine now.
The initial build from July, 1st, is on Maven Central now.

**Comment by ilgrosso** [comment]
Thank you very much @robertpanzer
